spring.application.name=shiftshield-enterprise

# Database configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/shiftshield?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=${JWT_SECRET:8a4a5840bd8319f3f98299292a836881c15f9d2d0b5e4c6c9a9d2d0b5e4c6c9a9d2d0b5e4c6c9a9d}
jwt.expiration=${JWT_EXPIRATION:86400000}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
